server:
  port: 8082

spring:
  application:
    name: report-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/report_services
    username: root
    password: 10092412
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 0
      batch-size: 16384
      linger-ms: 0
      buffer-memory: 33554432
      compression-type: snappy
  docker:
    compose:
          enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
          add-mappings: false

logging:
  file:
    name: logs/app.log
  level:
    com.backend.report-service: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Report Service
    version: 1.0.0
    description: Service for managing report information

jwt:
  public-key-location: keys/public.pem

internal:
  api-key: jHhHXen9L6sbH1ZjlO4iT8J6mt3qYVfc87juXtFpU6ybytNvaAIITl3v6v4cSZjd


