networks:
  microservices-networks:
    driver: bridge

services:
  # Base builder image
  base-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: "base-builder:latest"
    container_name: base-builder
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:9092
    # Không cần chạy container này, chỉ build image

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: "service-registry:latest"
    environment:
      - HOST_IP_ADDRESS= discovery-server
    container_name: ${DISCOVERY_SERVER:-discovery-server}
    ports:
      - "8761:8761"
    restart: unless-stopped
    networks:
      - microservices-networks

  gateway-service:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: "gateway-service:latest"
    container_name: ${API_GATEWAY:-api-gateway}
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - docker.env
    depends_on:
      discovery-server:
        condition: service_started
    networks:
      - microservices-networks

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: ${AUTH_SERVICE:-auth-service}
    image: "auth-service:latest"
    ports:
      - "8090:8090"
    restart: unless-stopped
    env_file:
      - docker.env
    depends_on:
      discovery-server:
        condition: service_started
    networks:
      - microservices-networks






