import HomeHeader from '@/components/shared/header/HomeHeader';
import HomeFooter from '@/components/shared/footer/HomeFooter';
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return(
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <HomeHeader />
        <main className="min-h-screen">
          {children}
        </main>
        <HomeFooter />
      </body>
    </html>
  );
}